#!/usr/bin/env php
<?php

define('TOKYO_START', microtime(true));

$autoloader = require file_exists(__DIR__ . '/vendor/autoload.php') ?  __DIR__ . '/vendor/autoload.php' : __DIR__ . '/../../autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$app->run();
