#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
HOMEPATH=$HOME

if [[ -L $SOURCE ]]
then
    DIR=$(php -r "echo dirname(realpath('$SOURCE'));")
else
    DIR="$( cd "$( dirname "$SOURCE" )" && pwd )"
fi

if [[ ! -f "$DIR/bootstrap/app.php" ]]
then
    DIR=$(php -r "echo realpath('$DIR/../eptic/tokyo');")
fi

SUDOCMDS=$(php "$DIR/bootstrap/app.php" "sudo-cmds")

if [[ -n $1 && $SUDOCMDS =~ $1 ]]
then
    if [[ "$EUID" -ne 0 ]]
    then
        sudo env TOKYO_DEBUG=$TOKYO_DEBUG HOME=$HOMEPATH $SOURCE "$@"
        exit 0
    fi
fi

php "$DIR/bootstrap/app.php" "$@"
