#!/usr/bin/env php
<?php

define('TOKYO_START', microtime(true));

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once getenv('HOME') . '/.composer/vendor/autoload.php';
}

$app = require_once __DIR__ . '/bootstrap/app.php';

$app->run();
